// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package setting

import (
	pb "github.com/LongMarch7/higo/service/admin/setting/pb"
	define "github.com/LongMarch7/higo/util/define"
	grpc "github.com/go-kit/kit/transport/grpc"
	grpc1 "google.golang.org/grpc"
)

// NewGRPCServer makes a set of endpoints available as a gRPC AddServer
type TestAlias = pb.Test
type GrpcServer struct {
	SayHelloHandler   grpc.Handler
	DeleteuserHandler grpc.Handler
}

func MakeRegisteFunc(srv pb.SettingServer) define.GrpcRegister {
	return func(s *grpc1.Server) {
		pb.RegisterSettingServer(s, srv)
	}
}
