// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/LongMarch7/higo/service/examples/hello/pb/hello.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HelloWorldRequest struct {
	S                    string   `protobuf:"bytes,1,opt,name=s,proto3" json:"s,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloWorldRequest) Reset()         { *m = HelloWorldRequest{} }
func (m *HelloWorldRequest) String() string { return proto.CompactTextString(m) }
func (*HelloWorldRequest) ProtoMessage()    {}
func (*HelloWorldRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b5f4d13745731bb4, []int{0}
}

func (m *HelloWorldRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloWorldRequest.Unmarshal(m, b)
}
func (m *HelloWorldRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloWorldRequest.Marshal(b, m, deterministic)
}
func (m *HelloWorldRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloWorldRequest.Merge(m, src)
}
func (m *HelloWorldRequest) XXX_Size() int {
	return xxx_messageInfo_HelloWorldRequest.Size(m)
}
func (m *HelloWorldRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloWorldRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloWorldRequest proto.InternalMessageInfo

func (m *HelloWorldRequest) GetS() string {
	if m != nil {
		return m.S
	}
	return ""
}

type HelloWorldReply struct {
	Rs                   string   `protobuf:"bytes,1,opt,name=rs,proto3" json:"rs,omitempty"`
	Err                  string   `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloWorldReply) Reset()         { *m = HelloWorldReply{} }
func (m *HelloWorldReply) String() string { return proto.CompactTextString(m) }
func (*HelloWorldReply) ProtoMessage()    {}
func (*HelloWorldReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_b5f4d13745731bb4, []int{1}
}

func (m *HelloWorldReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloWorldReply.Unmarshal(m, b)
}
func (m *HelloWorldReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloWorldReply.Marshal(b, m, deterministic)
}
func (m *HelloWorldReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloWorldReply.Merge(m, src)
}
func (m *HelloWorldReply) XXX_Size() int {
	return xxx_messageInfo_HelloWorldReply.Size(m)
}
func (m *HelloWorldReply) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloWorldReply.DiscardUnknown(m)
}

var xxx_messageInfo_HelloWorldReply proto.InternalMessageInfo

func (m *HelloWorldReply) GetRs() string {
	if m != nil {
		return m.Rs
	}
	return ""
}

func (m *HelloWorldReply) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func init() {
	proto.RegisterType((*HelloWorldRequest)(nil), "pb.HelloWorldRequest")
	proto.RegisterType((*HelloWorldReply)(nil), "pb.HelloWorldReply")
}

func init() {
	proto.RegisterFile("github.com/LongMarch7/higo/service/examples/hello/pb/hello.proto", fileDescriptor_b5f4d13745731bb4)
}

var fileDescriptor_b5f4d13745731bb4 = []byte{
	// 187 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x72, 0x48, 0xcf, 0x2c, 0xc9,
	0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0xf7, 0xc9, 0xcf, 0x4b, 0xf7, 0x4d, 0x2c, 0x4a, 0xce,
	0x30, 0xd7, 0xcf, 0xc8, 0x4c, 0xcf, 0xd7, 0x2f, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x4f,
	0xad, 0x48, 0xcc, 0x2d, 0xc8, 0x49, 0x2d, 0xd6, 0xcf, 0x48, 0xcd, 0xc9, 0xc9, 0xd7, 0x2f, 0x48,
	0x82, 0x30, 0xf4, 0x0a, 0x8a, 0xf2, 0x4b, 0xf2, 0x85, 0x98, 0x0a, 0x92, 0x94, 0x14, 0xb9, 0x04,
	0x3d, 0x40, 0x42, 0xe1, 0xf9, 0x45, 0x39, 0x29, 0x41, 0xa9, 0x85, 0xa5, 0xa9, 0xc5, 0x25, 0x42,
	0x3c, 0x5c, 0x8c, 0xc5, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x8c, 0xc5, 0x4a, 0xc6, 0x5c,
	0xfc, 0xc8, 0x4a, 0x0a, 0x72, 0x2a, 0x85, 0xf8, 0xb8, 0x98, 0x8a, 0x60, 0x2a, 0x98, 0x8a, 0x8a,
	0x85, 0x04, 0xb8, 0x98, 0x53, 0x8b, 0x8a, 0x24, 0x98, 0xc0, 0x02, 0x20, 0xa6, 0x91, 0x23, 0x17,
	0x2b, 0x58, 0x93, 0x90, 0x05, 0x17, 0x17, 0x42, 0xb7, 0x90, 0xa8, 0x5e, 0x41, 0x92, 0x1e, 0x86,
	0x85, 0x52, 0xc2, 0xe8, 0xc2, 0x05, 0x39, 0x95, 0x49, 0x6c, 0x60, 0x57, 0x1a, 0x03, 0x02, 0x00,
	0x00, 0xff, 0xff, 0x7c, 0xd2, 0x35, 0x06, 0xe9, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// HelloClient is the client API for Hello service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HelloClient interface {
	HelloWorld(ctx context.Context, in *HelloWorldRequest, opts ...grpc.CallOption) (*HelloWorldReply, error)
}

type helloClient struct {
	cc *grpc.ClientConn
}

func NewHelloClient(cc *grpc.ClientConn) HelloClient {
	return &helloClient{cc}
}

func (c *helloClient) HelloWorld(ctx context.Context, in *HelloWorldRequest, opts ...grpc.CallOption) (*HelloWorldReply, error) {
	out := new(HelloWorldReply)
	err := c.cc.Invoke(ctx, "/pb.Hello/HelloWorld", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HelloServer is the server API for Hello service.
type HelloServer interface {
	HelloWorld(context.Context, *HelloWorldRequest) (*HelloWorldReply, error)
}

// UnimplementedHelloServer can be embedded to have forward compatible implementations.
type UnimplementedHelloServer struct {
}

func (*UnimplementedHelloServer) HelloWorld(ctx context.Context, req *HelloWorldRequest) (*HelloWorldReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HelloWorld not implemented")
}

func RegisterHelloServer(s *grpc.Server, srv HelloServer) {
	s.RegisterService(&_Hello_serviceDesc, srv)
}

func _Hello_HelloWorld_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloWorldRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloServer).HelloWorld(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Hello/HelloWorld",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloServer).HelloWorld(ctx, req.(*HelloWorldRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Hello_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Hello",
	HandlerType: (*HelloServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HelloWorld",
			Handler:    _Hello_HelloWorld_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/LongMarch7/higo/service/examples/hello/pb/hello.proto",
}
