// Code generated by protoc-gen-go. DO NOT EDIT.
// source: web/pb/web.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HtmlCallRequest struct {
	Pattern              string   `protobuf:"bytes,1,opt,name=pattern,proto3" json:"pattern,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HtmlCallRequest) Reset()         { *m = HtmlCallRequest{} }
func (m *HtmlCallRequest) String() string { return proto.CompactTextString(m) }
func (*HtmlCallRequest) ProtoMessage()    {}
func (*HtmlCallRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8fd95c6658efcbe9, []int{0}
}

func (m *HtmlCallRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HtmlCallRequest.Unmarshal(m, b)
}
func (m *HtmlCallRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HtmlCallRequest.Marshal(b, m, deterministic)
}
func (m *HtmlCallRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HtmlCallRequest.Merge(m, src)
}
func (m *HtmlCallRequest) XXX_Size() int {
	return xxx_messageInfo_HtmlCallRequest.Size(m)
}
func (m *HtmlCallRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HtmlCallRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HtmlCallRequest proto.InternalMessageInfo

func (m *HtmlCallRequest) GetPattern() string {
	if m != nil {
		return m.Pattern
	}
	return ""
}

type HtmlCallReply struct {
	Rs                   string   `protobuf:"bytes,1,opt,name=rs,proto3" json:"rs,omitempty"`
	Err                  string   `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HtmlCallReply) Reset()         { *m = HtmlCallReply{} }
func (m *HtmlCallReply) String() string { return proto.CompactTextString(m) }
func (*HtmlCallReply) ProtoMessage()    {}
func (*HtmlCallReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_8fd95c6658efcbe9, []int{1}
}

func (m *HtmlCallReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HtmlCallReply.Unmarshal(m, b)
}
func (m *HtmlCallReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HtmlCallReply.Marshal(b, m, deterministic)
}
func (m *HtmlCallReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HtmlCallReply.Merge(m, src)
}
func (m *HtmlCallReply) XXX_Size() int {
	return xxx_messageInfo_HtmlCallReply.Size(m)
}
func (m *HtmlCallReply) XXX_DiscardUnknown() {
	xxx_messageInfo_HtmlCallReply.DiscardUnknown(m)
}

var xxx_messageInfo_HtmlCallReply proto.InternalMessageInfo

func (m *HtmlCallReply) GetRs() string {
	if m != nil {
		return m.Rs
	}
	return ""
}

func (m *HtmlCallReply) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type ApiCallRequest struct {
	Pattern              string   `protobuf:"bytes,1,opt,name=pattern,proto3" json:"pattern,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApiCallRequest) Reset()         { *m = ApiCallRequest{} }
func (m *ApiCallRequest) String() string { return proto.CompactTextString(m) }
func (*ApiCallRequest) ProtoMessage()    {}
func (*ApiCallRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8fd95c6658efcbe9, []int{2}
}

func (m *ApiCallRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApiCallRequest.Unmarshal(m, b)
}
func (m *ApiCallRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApiCallRequest.Marshal(b, m, deterministic)
}
func (m *ApiCallRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApiCallRequest.Merge(m, src)
}
func (m *ApiCallRequest) XXX_Size() int {
	return xxx_messageInfo_ApiCallRequest.Size(m)
}
func (m *ApiCallRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ApiCallRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ApiCallRequest proto.InternalMessageInfo

func (m *ApiCallRequest) GetPattern() string {
	if m != nil {
		return m.Pattern
	}
	return ""
}

type ApiCallReply struct {
	Rs                   string   `protobuf:"bytes,1,opt,name=rs,proto3" json:"rs,omitempty"`
	Err                  string   `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApiCallReply) Reset()         { *m = ApiCallReply{} }
func (m *ApiCallReply) String() string { return proto.CompactTextString(m) }
func (*ApiCallReply) ProtoMessage()    {}
func (*ApiCallReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_8fd95c6658efcbe9, []int{3}
}

func (m *ApiCallReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApiCallReply.Unmarshal(m, b)
}
func (m *ApiCallReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApiCallReply.Marshal(b, m, deterministic)
}
func (m *ApiCallReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApiCallReply.Merge(m, src)
}
func (m *ApiCallReply) XXX_Size() int {
	return xxx_messageInfo_ApiCallReply.Size(m)
}
func (m *ApiCallReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ApiCallReply.DiscardUnknown(m)
}

var xxx_messageInfo_ApiCallReply proto.InternalMessageInfo

func (m *ApiCallReply) GetRs() string {
	if m != nil {
		return m.Rs
	}
	return ""
}

func (m *ApiCallReply) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func init() {
	proto.RegisterType((*HtmlCallRequest)(nil), "pb.HtmlCallRequest")
	proto.RegisterType((*HtmlCallReply)(nil), "pb.HtmlCallReply")
	proto.RegisterType((*ApiCallRequest)(nil), "pb.ApiCallRequest")
	proto.RegisterType((*ApiCallReply)(nil), "pb.ApiCallReply")
}

func init() { proto.RegisterFile("web/pb/web.proto", fileDescriptor_8fd95c6658efcbe9) }

var fileDescriptor_8fd95c6658efcbe9 = []byte{
	// 186 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x28, 0x4f, 0x4d, 0xd2,
	0x2f, 0x48, 0xd2, 0x2f, 0x4f, 0x4d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48,
	0x52, 0xd2, 0xe6, 0xe2, 0xf7, 0x28, 0xc9, 0xcd, 0x71, 0x4e, 0xcc, 0xc9, 0x09, 0x4a, 0x2d, 0x2c,
	0x4d, 0x2d, 0x2e, 0x11, 0x92, 0xe0, 0x62, 0x2f, 0x48, 0x2c, 0x29, 0x49, 0x2d, 0xca, 0x93, 0x60,
	0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x82, 0x71, 0x95, 0x0c, 0xb9, 0x78, 0x11, 0x8a, 0x0b, 0x72, 0x2a,
	0x85, 0xf8, 0xb8, 0x98, 0x8a, 0x8a, 0xa1, 0xaa, 0x98, 0x8a, 0x8a, 0x85, 0x04, 0xb8, 0x98, 0x53,
	0x8b, 0x8a, 0x24, 0x98, 0xc0, 0x02, 0x20, 0xa6, 0x92, 0x16, 0x17, 0x9f, 0x63, 0x41, 0x26, 0x71,
	0xc6, 0x1b, 0x70, 0xf1, 0xc0, 0xd5, 0x12, 0x65, 0xba, 0x51, 0x16, 0x17, 0x73, 0x78, 0x6a, 0x92,
	0x90, 0x11, 0x17, 0x07, 0xcc, 0x5d, 0x42, 0xc2, 0x7a, 0x05, 0x49, 0x7a, 0x68, 0x5e, 0x92, 0x12,
	0x44, 0x15, 0x04, 0x19, 0xae, 0xcf, 0xc5, 0x0e, 0xb5, 0x4c, 0x48, 0x08, 0x24, 0x8b, 0xea, 0x4a,
	0x29, 0x01, 0x14, 0xb1, 0x82, 0x9c, 0xca, 0x24, 0x36, 0x70, 0xa0, 0x19, 0x03, 0x02, 0x00, 0x00,
	0xff, 0xff, 0x14, 0x8d, 0xfe, 0xdf, 0x48, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// WebClient is the client API for Web service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WebClient interface {
	HtmlCall(ctx context.Context, in *HtmlCallRequest, opts ...grpc.CallOption) (*HtmlCallReply, error)
	ApiCall(ctx context.Context, in *ApiCallRequest, opts ...grpc.CallOption) (*ApiCallReply, error)
}

type webClient struct {
	cc *grpc.ClientConn
}

func NewWebClient(cc *grpc.ClientConn) WebClient {
	return &webClient{cc}
}

func (c *webClient) HtmlCall(ctx context.Context, in *HtmlCallRequest, opts ...grpc.CallOption) (*HtmlCallReply, error) {
	out := new(HtmlCallReply)
	err := c.cc.Invoke(ctx, "/pb.Web/HtmlCall", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webClient) ApiCall(ctx context.Context, in *ApiCallRequest, opts ...grpc.CallOption) (*ApiCallReply, error) {
	out := new(ApiCallReply)
	err := c.cc.Invoke(ctx, "/pb.Web/ApiCall", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WebServer is the server API for Web service.
type WebServer interface {
	HtmlCall(context.Context, *HtmlCallRequest) (*HtmlCallReply, error)
	ApiCall(context.Context, *ApiCallRequest) (*ApiCallReply, error)
}

// UnimplementedWebServer can be embedded to have forward compatible implementations.
type UnimplementedWebServer struct {
}

func (*UnimplementedWebServer) HtmlCall(ctx context.Context, req *HtmlCallRequest) (*HtmlCallReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HtmlCall not implemented")
}
func (*UnimplementedWebServer) ApiCall(ctx context.Context, req *ApiCallRequest) (*ApiCallReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApiCall not implemented")
}

func RegisterWebServer(s *grpc.Server, srv WebServer) {
	s.RegisterService(&_Web_serviceDesc, srv)
}

func _Web_HtmlCall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HtmlCallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebServer).HtmlCall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Web/HtmlCall",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebServer).HtmlCall(ctx, req.(*HtmlCallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Web_ApiCall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApiCallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebServer).ApiCall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Web/ApiCall",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebServer).ApiCall(ctx, req.(*ApiCallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Web_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Web",
	HandlerType: (*WebServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HtmlCall",
			Handler:    _Web_HtmlCall_Handler,
		},
		{
			MethodName: "ApiCall",
			Handler:    _Web_ApiCall_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "web/pb/web.proto",
}
