// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/LongMarch7/higo/service/admin/setting/pb/setting.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SayHelloRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SayHelloRequest) Reset()         { *m = SayHelloRequest{} }
func (m *SayHelloRequest) String() string { return proto.CompactTextString(m) }
func (*SayHelloRequest) ProtoMessage()    {}
func (*SayHelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b42b6484bb5a24ed, []int{0}
}

func (m *SayHelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SayHelloRequest.Unmarshal(m, b)
}
func (m *SayHelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SayHelloRequest.Marshal(b, m, deterministic)
}
func (m *SayHelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SayHelloRequest.Merge(m, src)
}
func (m *SayHelloRequest) XXX_Size() int {
	return xxx_messageInfo_SayHelloRequest.Size(m)
}
func (m *SayHelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SayHelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SayHelloRequest proto.InternalMessageInfo

type SayHelloReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SayHelloReply) Reset()         { *m = SayHelloReply{} }
func (m *SayHelloReply) String() string { return proto.CompactTextString(m) }
func (*SayHelloReply) ProtoMessage()    {}
func (*SayHelloReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_b42b6484bb5a24ed, []int{1}
}

func (m *SayHelloReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SayHelloReply.Unmarshal(m, b)
}
func (m *SayHelloReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SayHelloReply.Marshal(b, m, deterministic)
}
func (m *SayHelloReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SayHelloReply.Merge(m, src)
}
func (m *SayHelloReply) XXX_Size() int {
	return xxx_messageInfo_SayHelloReply.Size(m)
}
func (m *SayHelloReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SayHelloReply.DiscardUnknown(m)
}

var xxx_messageInfo_SayHelloReply proto.InternalMessageInfo

type DeleteuserRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteuserRequest) Reset()         { *m = DeleteuserRequest{} }
func (m *DeleteuserRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteuserRequest) ProtoMessage()    {}
func (*DeleteuserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b42b6484bb5a24ed, []int{2}
}

func (m *DeleteuserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteuserRequest.Unmarshal(m, b)
}
func (m *DeleteuserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteuserRequest.Marshal(b, m, deterministic)
}
func (m *DeleteuserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteuserRequest.Merge(m, src)
}
func (m *DeleteuserRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteuserRequest.Size(m)
}
func (m *DeleteuserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteuserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteuserRequest proto.InternalMessageInfo

type DeleteuserReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteuserReply) Reset()         { *m = DeleteuserReply{} }
func (m *DeleteuserReply) String() string { return proto.CompactTextString(m) }
func (*DeleteuserReply) ProtoMessage()    {}
func (*DeleteuserReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_b42b6484bb5a24ed, []int{3}
}

func (m *DeleteuserReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteuserReply.Unmarshal(m, b)
}
func (m *DeleteuserReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteuserReply.Marshal(b, m, deterministic)
}
func (m *DeleteuserReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteuserReply.Merge(m, src)
}
func (m *DeleteuserReply) XXX_Size() int {
	return xxx_messageInfo_DeleteuserReply.Size(m)
}
func (m *DeleteuserReply) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteuserReply.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteuserReply proto.InternalMessageInfo

func init() {
	proto.RegisterType((*SayHelloRequest)(nil), "pb.SayHelloRequest")
	proto.RegisterType((*SayHelloReply)(nil), "pb.SayHelloReply")
	proto.RegisterType((*DeleteuserRequest)(nil), "pb.DeleteuserRequest")
	proto.RegisterType((*DeleteuserReply)(nil), "pb.DeleteuserReply")
}

func init() {
	proto.RegisterFile("github.com/LongMarch7/higo/service/admin/setting/pb/setting.proto", fileDescriptor_b42b6484bb5a24ed)
}

var fileDescriptor_b42b6484bb5a24ed = []byte{
	// 192 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x8f, 0xc1, 0x8a, 0xc2, 0x30,
	0x10, 0x86, 0x61, 0x0f, 0xbb, 0xcb, 0xc0, 0x52, 0x92, 0xb2, 0x97, 0x1e, 0xfb, 0x00, 0x09, 0x74,
	0x0f, 0xeb, 0x55, 0xf0, 0xe0, 0x41, 0x2f, 0xf6, 0x09, 0x9a, 0x3a, 0xa4, 0x81, 0xb4, 0x19, 0x93,
	0x54, 0xc9, 0xdb, 0x8b, 0x4a, 0xa9, 0xd6, 0xdb, 0xf0, 0xf1, 0xf3, 0x7d, 0x0c, 0xac, 0xb5, 0x89,
	0xdd, 0xa8, 0x44, 0xeb, 0x7a, 0xb9, 0x73, 0x83, 0xde, 0x37, 0xbe, 0xed, 0xfe, 0x65, 0x67, 0xb4,
	0x93, 0x01, 0xfd, 0xd9, 0xb4, 0x28, 0x9b, 0x63, 0x6f, 0x06, 0x19, 0x30, 0x46, 0x33, 0x68, 0x49,
	0x6a, 0x3a, 0x05, 0x79, 0x17, 0x1d, 0xff, 0x20, 0x55, 0x32, 0xc8, 0xea, 0x26, 0x6d, 0xd1, 0x5a,
	0x77, 0xc0, 0xd3, 0x88, 0x21, 0x96, 0x19, 0xfc, 0xcc, 0x88, 0x6c, 0x2a, 0x73, 0x60, 0x1b, 0xb4,
	0x18, 0x71, 0x0c, 0xe8, 0xa7, 0x15, 0x83, 0xec, 0x19, 0x92, 0x4d, 0xd5, 0x05, 0xbe, 0xea, 0x47,
	0x80, 0x57, 0xf0, 0x3d, 0x39, 0x78, 0x2e, 0x48, 0x89, 0x45, 0xa4, 0x60, 0xaf, 0x90, 0x6c, 0xe2,
	0x2b, 0x80, 0xd9, 0xc8, 0x7f, 0x6f, 0x83, 0xb7, 0x6c, 0x91, 0x2f, 0x31, 0xd9, 0xa4, 0x3e, 0xef,
	0xff, 0xfc, 0x5d, 0x03, 0x00, 0x00, 0xff, 0xff, 0x51, 0x95, 0xa2, 0x52, 0x14, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SettingClient is the client API for Setting service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SettingClient interface {
	SayHello(ctx context.Context, in *SayHelloRequest, opts ...grpc.CallOption) (*SayHelloReply, error)
	Deleteuser(ctx context.Context, in *DeleteuserRequest, opts ...grpc.CallOption) (*DeleteuserReply, error)
}

type settingClient struct {
	cc *grpc.ClientConn
}

func NewSettingClient(cc *grpc.ClientConn) SettingClient {
	return &settingClient{cc}
}

func (c *settingClient) SayHello(ctx context.Context, in *SayHelloRequest, opts ...grpc.CallOption) (*SayHelloReply, error) {
	out := new(SayHelloReply)
	err := c.cc.Invoke(ctx, "/pb.Setting/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *settingClient) Deleteuser(ctx context.Context, in *DeleteuserRequest, opts ...grpc.CallOption) (*DeleteuserReply, error) {
	out := new(DeleteuserReply)
	err := c.cc.Invoke(ctx, "/pb.Setting/Deleteuser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SettingServer is the server API for Setting service.
type SettingServer interface {
	SayHello(context.Context, *SayHelloRequest) (*SayHelloReply, error)
	Deleteuser(context.Context, *DeleteuserRequest) (*DeleteuserReply, error)
}

// UnimplementedSettingServer can be embedded to have forward compatible implementations.
type UnimplementedSettingServer struct {
}

func (*UnimplementedSettingServer) SayHello(ctx context.Context, req *SayHelloRequest) (*SayHelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (*UnimplementedSettingServer) Deleteuser(ctx context.Context, req *DeleteuserRequest) (*DeleteuserReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Deleteuser not implemented")
}

func RegisterSettingServer(s *grpc.Server, srv SettingServer) {
	s.RegisterService(&_Setting_serviceDesc, srv)
}

func _Setting_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SayHelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SettingServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Setting/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SettingServer).SayHello(ctx, req.(*SayHelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Setting_Deleteuser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteuserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SettingServer).Deleteuser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Setting/Deleteuser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SettingServer).Deleteuser(ctx, req.(*DeleteuserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Setting_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Setting",
	HandlerType: (*SettingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Setting_SayHello_Handler,
		},
		{
			MethodName: "Deleteuser",
			Handler:    _Setting_Deleteuser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/LongMarch7/higo/service/admin/setting/pb/setting.proto",
}
