// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/LongMarch7/higo/service/admin/setting/pb/setting.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SayHelloRequest struct {
	S                    *Test    `protobuf:"bytes,1,opt,name=s,proto3" json:"s,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SayHelloRequest) Reset()         { *m = SayHelloRequest{} }
func (m *SayHelloRequest) String() string { return proto.CompactTextString(m) }
func (*SayHelloRequest) ProtoMessage()    {}
func (*SayHelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b42b6484bb5a24ed, []int{0}
}

func (m *SayHelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SayHelloRequest.Unmarshal(m, b)
}
func (m *SayHelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SayHelloRequest.Marshal(b, m, deterministic)
}
func (m *SayHelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SayHelloRequest.Merge(m, src)
}
func (m *SayHelloRequest) XXX_Size() int {
	return xxx_messageInfo_SayHelloRequest.Size(m)
}
func (m *SayHelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SayHelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SayHelloRequest proto.InternalMessageInfo

func (m *SayHelloRequest) GetS() *Test {
	if m != nil {
		return m.S
	}
	return nil
}

type SayHelloReply struct {
	Rs                   string   `protobuf:"bytes,1,opt,name=rs,proto3" json:"rs,omitempty"`
	Err                  string   `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SayHelloReply) Reset()         { *m = SayHelloReply{} }
func (m *SayHelloReply) String() string { return proto.CompactTextString(m) }
func (*SayHelloReply) ProtoMessage()    {}
func (*SayHelloReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_b42b6484bb5a24ed, []int{1}
}

func (m *SayHelloReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SayHelloReply.Unmarshal(m, b)
}
func (m *SayHelloReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SayHelloReply.Marshal(b, m, deterministic)
}
func (m *SayHelloReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SayHelloReply.Merge(m, src)
}
func (m *SayHelloReply) XXX_Size() int {
	return xxx_messageInfo_SayHelloReply.Size(m)
}
func (m *SayHelloReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SayHelloReply.DiscardUnknown(m)
}

var xxx_messageInfo_SayHelloReply proto.InternalMessageInfo

func (m *SayHelloReply) GetRs() string {
	if m != nil {
		return m.Rs
	}
	return ""
}

func (m *SayHelloReply) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type DeleteuserRequest struct {
	S                    string   `protobuf:"bytes,1,opt,name=s,proto3" json:"s,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteuserRequest) Reset()         { *m = DeleteuserRequest{} }
func (m *DeleteuserRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteuserRequest) ProtoMessage()    {}
func (*DeleteuserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b42b6484bb5a24ed, []int{2}
}

func (m *DeleteuserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteuserRequest.Unmarshal(m, b)
}
func (m *DeleteuserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteuserRequest.Marshal(b, m, deterministic)
}
func (m *DeleteuserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteuserRequest.Merge(m, src)
}
func (m *DeleteuserRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteuserRequest.Size(m)
}
func (m *DeleteuserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteuserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteuserRequest proto.InternalMessageInfo

func (m *DeleteuserRequest) GetS() string {
	if m != nil {
		return m.S
	}
	return ""
}

type DeleteuserReply struct {
	Rs                   string   `protobuf:"bytes,1,opt,name=rs,proto3" json:"rs,omitempty"`
	Err                  string   `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteuserReply) Reset()         { *m = DeleteuserReply{} }
func (m *DeleteuserReply) String() string { return proto.CompactTextString(m) }
func (*DeleteuserReply) ProtoMessage()    {}
func (*DeleteuserReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_b42b6484bb5a24ed, []int{3}
}

func (m *DeleteuserReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteuserReply.Unmarshal(m, b)
}
func (m *DeleteuserReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteuserReply.Marshal(b, m, deterministic)
}
func (m *DeleteuserReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteuserReply.Merge(m, src)
}
func (m *DeleteuserReply) XXX_Size() int {
	return xxx_messageInfo_DeleteuserReply.Size(m)
}
func (m *DeleteuserReply) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteuserReply.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteuserReply proto.InternalMessageInfo

func (m *DeleteuserReply) GetRs() string {
	if m != nil {
		return m.Rs
	}
	return ""
}

func (m *DeleteuserReply) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type Test struct {
	Test1                string   `protobuf:"bytes,1,opt,name=test1,proto3" json:"test1,omitempty"`
	Test2                int32    `protobuf:"varint,3,opt,name=test2,proto3" json:"test2,omitempty"`
	Test3                bool     `protobuf:"varint,4,opt,name=test3,proto3" json:"test3,omitempty"`
	Test4                []string `protobuf:"bytes,5,rep,name=test4,proto3" json:"test4,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Test) Reset()         { *m = Test{} }
func (m *Test) String() string { return proto.CompactTextString(m) }
func (*Test) ProtoMessage()    {}
func (*Test) Descriptor() ([]byte, []int) {
	return fileDescriptor_b42b6484bb5a24ed, []int{4}
}

func (m *Test) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Test.Unmarshal(m, b)
}
func (m *Test) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Test.Marshal(b, m, deterministic)
}
func (m *Test) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Test.Merge(m, src)
}
func (m *Test) XXX_Size() int {
	return xxx_messageInfo_Test.Size(m)
}
func (m *Test) XXX_DiscardUnknown() {
	xxx_messageInfo_Test.DiscardUnknown(m)
}

var xxx_messageInfo_Test proto.InternalMessageInfo

func (m *Test) GetTest1() string {
	if m != nil {
		return m.Test1
	}
	return ""
}

func (m *Test) GetTest2() int32 {
	if m != nil {
		return m.Test2
	}
	return 0
}

func (m *Test) GetTest3() bool {
	if m != nil {
		return m.Test3
	}
	return false
}

func (m *Test) GetTest4() []string {
	if m != nil {
		return m.Test4
	}
	return nil
}

func init() {
	proto.RegisterType((*SayHelloRequest)(nil), "pb.SayHelloRequest")
	proto.RegisterType((*SayHelloReply)(nil), "pb.SayHelloReply")
	proto.RegisterType((*DeleteuserRequest)(nil), "pb.DeleteuserRequest")
	proto.RegisterType((*DeleteuserReply)(nil), "pb.DeleteuserReply")
	proto.RegisterType((*Test)(nil), "pb.Test")
}

func init() {
	proto.RegisterFile("github.com/LongMarch7/higo/service/admin/setting/pb/setting.proto", fileDescriptor_b42b6484bb5a24ed)
}

var fileDescriptor_b42b6484bb5a24ed = []byte{
	// 286 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0xcf, 0x4f, 0xab, 0x40,
	0x14, 0x85, 0x33, 0xb4, 0x7d, 0x8f, 0x5e, 0x7f, 0xd4, 0x4e, 0xd5, 0x90, 0xae, 0x90, 0x15, 0x6e,
	0x98, 0x14, 0x9a, 0xe8, 0xd6, 0xc4, 0x85, 0x0b, 0xdd, 0x50, 0xd7, 0x26, 0x80, 0x37, 0x40, 0x42,
	0x99, 0x71, 0x66, 0xd0, 0xf0, 0xdf, 0x9b, 0x29, 0x4e, 0xaa, 0x75, 0xe3, 0xee, 0xf2, 0xe5, 0xe4,
	0x0b, 0xe7, 0x0c, 0xdc, 0x95, 0xb5, 0xae, 0xba, 0x3c, 0x2a, 0xf8, 0x96, 0x3d, 0xf2, 0xb6, 0x7c,
	0xca, 0x64, 0x51, 0xdd, 0xb0, 0xaa, 0x2e, 0x39, 0x53, 0x28, 0xdf, 0xeb, 0x02, 0x59, 0xf6, 0xba,
	0xad, 0x5b, 0xa6, 0x50, 0xeb, 0xba, 0x2d, 0x99, 0xc8, 0xed, 0x19, 0x09, 0xc9, 0x35, 0xa7, 0x8e,
	0xc8, 0x83, 0x6b, 0x98, 0x6d, 0xb2, 0xfe, 0x01, 0x9b, 0x86, 0xa7, 0xf8, 0xd6, 0xa1, 0xd2, 0xf4,
	0x12, 0x88, 0xf2, 0x88, 0x4f, 0xc2, 0xa3, 0xd8, 0x8d, 0x44, 0x1e, 0x3d, 0xa3, 0xd2, 0x29, 0x51,
	0xc1, 0x0a, 0x4e, 0xf6, 0x51, 0xd1, 0xf4, 0xf4, 0x14, 0x1c, 0x39, 0x24, 0xa7, 0xa9, 0x23, 0x15,
	0x3d, 0x83, 0x11, 0x4a, 0xe9, 0x39, 0x3b, 0x60, 0xce, 0xe0, 0x0a, 0xe6, 0xf7, 0xd8, 0xa0, 0xc6,
	0x4e, 0xa1, 0xb4, 0xfe, 0x63, 0xeb, 0x9f, 0x1a, 0x6b, 0x02, 0xb3, 0xef, 0x91, 0xbf, 0x79, 0x5f,
	0x60, 0x6c, 0xfe, 0x8a, 0x9e, 0xc3, 0x44, 0xa3, 0xd2, 0xab, 0xaf, 0xf0, 0xf0, 0x61, 0x69, 0xec,
	0x8d, 0x7c, 0x12, 0x4e, 0x06, 0x1a, 0x5b, 0x9a, 0x78, 0x63, 0x9f, 0x84, 0xee, 0x40, 0x13, 0x4b,
	0xd7, 0xde, 0xc4, 0x1f, 0x59, 0xc3, 0x3a, 0xfe, 0x80, 0xff, 0x9b, 0x61, 0x2a, 0x1a, 0x83, 0x6b,
	0x5b, 0xd3, 0x85, 0x99, 0xe3, 0x60, 0xae, 0xe5, 0xfc, 0x27, 0x34, 0x05, 0x6e, 0x01, 0xf6, 0x9d,
	0xe8, 0x85, 0x09, 0xfc, 0x9a, 0x61, 0xb9, 0x38, 0xc4, 0xa2, 0xe9, 0xf3, 0x7f, 0xbb, 0x97, 0x49,
	0x3e, 0x03, 0x00, 0x00, 0xff, 0xff, 0x1d, 0xd9, 0x81, 0x09, 0xde, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SettingClient is the client API for Setting service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SettingClient interface {
	SayHello(ctx context.Context, in *SayHelloRequest, opts ...grpc.CallOption) (*SayHelloReply, error)
	Deleteuser(ctx context.Context, in *DeleteuserRequest, opts ...grpc.CallOption) (*DeleteuserReply, error)
}

type settingClient struct {
	cc *grpc.ClientConn
}

func NewSettingClient(cc *grpc.ClientConn) SettingClient {
	return &settingClient{cc}
}

func (c *settingClient) SayHello(ctx context.Context, in *SayHelloRequest, opts ...grpc.CallOption) (*SayHelloReply, error) {
	out := new(SayHelloReply)
	err := c.cc.Invoke(ctx, "/pb.Setting/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *settingClient) Deleteuser(ctx context.Context, in *DeleteuserRequest, opts ...grpc.CallOption) (*DeleteuserReply, error) {
	out := new(DeleteuserReply)
	err := c.cc.Invoke(ctx, "/pb.Setting/Deleteuser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SettingServer is the server API for Setting service.
type SettingServer interface {
	SayHello(context.Context, *SayHelloRequest) (*SayHelloReply, error)
	Deleteuser(context.Context, *DeleteuserRequest) (*DeleteuserReply, error)
}

// UnimplementedSettingServer can be embedded to have forward compatible implementations.
type UnimplementedSettingServer struct {
}

func (*UnimplementedSettingServer) SayHello(ctx context.Context, req *SayHelloRequest) (*SayHelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (*UnimplementedSettingServer) Deleteuser(ctx context.Context, req *DeleteuserRequest) (*DeleteuserReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Deleteuser not implemented")
}

func RegisterSettingServer(s *grpc.Server, srv SettingServer) {
	s.RegisterService(&_Setting_serviceDesc, srv)
}

func _Setting_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SayHelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SettingServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Setting/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SettingServer).SayHello(ctx, req.(*SayHelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Setting_Deleteuser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteuserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SettingServer).Deleteuser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Setting/Deleteuser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SettingServer).Deleteuser(ctx, req.(*DeleteuserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Setting_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Setting",
	HandlerType: (*SettingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Setting_SayHello_Handler,
		},
		{
			MethodName: "Deleteuser",
			Handler:    _Setting_Deleteuser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/LongMarch7/higo/service/admin/setting/pb/setting.proto",
}
