// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package test

import (
	pb "github.com/LongMarch7/higo/service/examples/test/pb"
	define "github.com/LongMarch7/higo/util/define"
	grpc "github.com/go-kit/kit/transport/grpc"
	grpc1 "google.golang.org/grpc"
)

// NewGRPCServer makes a set of endpoints available as a gRPC AddServer
type TestStrucAlias = pb.TestStruc
type GrpcServer struct {
	SayHelloHandler   grpc.Handler
	DeleteuserHandler grpc.Handler
	TestArrayHandler  grpc.Handler
}

func MakeRegisteFunc(srv pb.TestServer) define.GrpcRegister {
	return func(s *grpc1.Server) {
		pb.RegisterTestServer(s, srv)
	}
}
