// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/LongMarch7/higo/service/examples/test/pb/test.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SayHelloRequest struct {
	S                    *TestStruc `protobuf:"bytes,1,opt,name=s,proto3" json:"s,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SayHelloRequest) Reset()         { *m = SayHelloRequest{} }
func (m *SayHelloRequest) String() string { return proto.CompactTextString(m) }
func (*SayHelloRequest) ProtoMessage()    {}
func (*SayHelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9202bf9adf0933a3, []int{0}
}

func (m *SayHelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SayHelloRequest.Unmarshal(m, b)
}
func (m *SayHelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SayHelloRequest.Marshal(b, m, deterministic)
}
func (m *SayHelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SayHelloRequest.Merge(m, src)
}
func (m *SayHelloRequest) XXX_Size() int {
	return xxx_messageInfo_SayHelloRequest.Size(m)
}
func (m *SayHelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SayHelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SayHelloRequest proto.InternalMessageInfo

func (m *SayHelloRequest) GetS() *TestStruc {
	if m != nil {
		return m.S
	}
	return nil
}

type SayHelloReply struct {
	Rs                   string   `protobuf:"bytes,1,opt,name=rs,proto3" json:"rs,omitempty"`
	Err                  string   `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SayHelloReply) Reset()         { *m = SayHelloReply{} }
func (m *SayHelloReply) String() string { return proto.CompactTextString(m) }
func (*SayHelloReply) ProtoMessage()    {}
func (*SayHelloReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_9202bf9adf0933a3, []int{1}
}

func (m *SayHelloReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SayHelloReply.Unmarshal(m, b)
}
func (m *SayHelloReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SayHelloReply.Marshal(b, m, deterministic)
}
func (m *SayHelloReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SayHelloReply.Merge(m, src)
}
func (m *SayHelloReply) XXX_Size() int {
	return xxx_messageInfo_SayHelloReply.Size(m)
}
func (m *SayHelloReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SayHelloReply.DiscardUnknown(m)
}

var xxx_messageInfo_SayHelloReply proto.InternalMessageInfo

func (m *SayHelloReply) GetRs() string {
	if m != nil {
		return m.Rs
	}
	return ""
}

func (m *SayHelloReply) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type DeleteuserRequest struct {
	S                    string   `protobuf:"bytes,1,opt,name=s,proto3" json:"s,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteuserRequest) Reset()         { *m = DeleteuserRequest{} }
func (m *DeleteuserRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteuserRequest) ProtoMessage()    {}
func (*DeleteuserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9202bf9adf0933a3, []int{2}
}

func (m *DeleteuserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteuserRequest.Unmarshal(m, b)
}
func (m *DeleteuserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteuserRequest.Marshal(b, m, deterministic)
}
func (m *DeleteuserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteuserRequest.Merge(m, src)
}
func (m *DeleteuserRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteuserRequest.Size(m)
}
func (m *DeleteuserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteuserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteuserRequest proto.InternalMessageInfo

func (m *DeleteuserRequest) GetS() string {
	if m != nil {
		return m.S
	}
	return ""
}

type DeleteuserReply struct {
	Rs                   string   `protobuf:"bytes,1,opt,name=rs,proto3" json:"rs,omitempty"`
	Err                  string   `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteuserReply) Reset()         { *m = DeleteuserReply{} }
func (m *DeleteuserReply) String() string { return proto.CompactTextString(m) }
func (*DeleteuserReply) ProtoMessage()    {}
func (*DeleteuserReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_9202bf9adf0933a3, []int{3}
}

func (m *DeleteuserReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteuserReply.Unmarshal(m, b)
}
func (m *DeleteuserReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteuserReply.Marshal(b, m, deterministic)
}
func (m *DeleteuserReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteuserReply.Merge(m, src)
}
func (m *DeleteuserReply) XXX_Size() int {
	return xxx_messageInfo_DeleteuserReply.Size(m)
}
func (m *DeleteuserReply) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteuserReply.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteuserReply proto.InternalMessageInfo

func (m *DeleteuserReply) GetRs() string {
	if m != nil {
		return m.Rs
	}
	return ""
}

func (m *DeleteuserReply) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type TestArrayRequest struct {
	S                    []*TestStruc `protobuf:"bytes,1,rep,name=s,proto3" json:"s,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *TestArrayRequest) Reset()         { *m = TestArrayRequest{} }
func (m *TestArrayRequest) String() string { return proto.CompactTextString(m) }
func (*TestArrayRequest) ProtoMessage()    {}
func (*TestArrayRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9202bf9adf0933a3, []int{4}
}

func (m *TestArrayRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestArrayRequest.Unmarshal(m, b)
}
func (m *TestArrayRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestArrayRequest.Marshal(b, m, deterministic)
}
func (m *TestArrayRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestArrayRequest.Merge(m, src)
}
func (m *TestArrayRequest) XXX_Size() int {
	return xxx_messageInfo_TestArrayRequest.Size(m)
}
func (m *TestArrayRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TestArrayRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TestArrayRequest proto.InternalMessageInfo

func (m *TestArrayRequest) GetS() []*TestStruc {
	if m != nil {
		return m.S
	}
	return nil
}

type TestArrayReply struct {
	Rs                   string   `protobuf:"bytes,1,opt,name=rs,proto3" json:"rs,omitempty"`
	Err                  string   `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestArrayReply) Reset()         { *m = TestArrayReply{} }
func (m *TestArrayReply) String() string { return proto.CompactTextString(m) }
func (*TestArrayReply) ProtoMessage()    {}
func (*TestArrayReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_9202bf9adf0933a3, []int{5}
}

func (m *TestArrayReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestArrayReply.Unmarshal(m, b)
}
func (m *TestArrayReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestArrayReply.Marshal(b, m, deterministic)
}
func (m *TestArrayReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestArrayReply.Merge(m, src)
}
func (m *TestArrayReply) XXX_Size() int {
	return xxx_messageInfo_TestArrayReply.Size(m)
}
func (m *TestArrayReply) XXX_DiscardUnknown() {
	xxx_messageInfo_TestArrayReply.DiscardUnknown(m)
}

var xxx_messageInfo_TestArrayReply proto.InternalMessageInfo

func (m *TestArrayReply) GetRs() string {
	if m != nil {
		return m.Rs
	}
	return ""
}

func (m *TestArrayReply) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type TestStruc struct {
	Test1                string   `protobuf:"bytes,1,opt,name=test1,proto3" json:"test1,omitempty"`
	Test2                int32    `protobuf:"varint,3,opt,name=test2,proto3" json:"test2,omitempty"`
	Test3                bool     `protobuf:"varint,4,opt,name=test3,proto3" json:"test3,omitempty"`
	Test4                []string `protobuf:"bytes,5,rep,name=test4,proto3" json:"test4,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestStruc) Reset()         { *m = TestStruc{} }
func (m *TestStruc) String() string { return proto.CompactTextString(m) }
func (*TestStruc) ProtoMessage()    {}
func (*TestStruc) Descriptor() ([]byte, []int) {
	return fileDescriptor_9202bf9adf0933a3, []int{6}
}

func (m *TestStruc) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestStruc.Unmarshal(m, b)
}
func (m *TestStruc) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestStruc.Marshal(b, m, deterministic)
}
func (m *TestStruc) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestStruc.Merge(m, src)
}
func (m *TestStruc) XXX_Size() int {
	return xxx_messageInfo_TestStruc.Size(m)
}
func (m *TestStruc) XXX_DiscardUnknown() {
	xxx_messageInfo_TestStruc.DiscardUnknown(m)
}

var xxx_messageInfo_TestStruc proto.InternalMessageInfo

func (m *TestStruc) GetTest1() string {
	if m != nil {
		return m.Test1
	}
	return ""
}

func (m *TestStruc) GetTest2() int32 {
	if m != nil {
		return m.Test2
	}
	return 0
}

func (m *TestStruc) GetTest3() bool {
	if m != nil {
		return m.Test3
	}
	return false
}

func (m *TestStruc) GetTest4() []string {
	if m != nil {
		return m.Test4
	}
	return nil
}

func init() {
	proto.RegisterType((*SayHelloRequest)(nil), "pb.SayHelloRequest")
	proto.RegisterType((*SayHelloReply)(nil), "pb.SayHelloReply")
	proto.RegisterType((*DeleteuserRequest)(nil), "pb.DeleteuserRequest")
	proto.RegisterType((*DeleteuserReply)(nil), "pb.DeleteuserReply")
	proto.RegisterType((*TestArrayRequest)(nil), "pb.TestArrayRequest")
	proto.RegisterType((*TestArrayReply)(nil), "pb.TestArrayReply")
	proto.RegisterType((*TestStruc)(nil), "pb.TestStruc")
}

func init() {
	proto.RegisterFile("github.com/LongMarch7/higo/service/examples/test/pb/test.proto", fileDescriptor_9202bf9adf0933a3)
}

var fileDescriptor_9202bf9adf0933a3 = []byte{
	// 328 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xbf, 0x4e, 0xf3, 0x30,
	0x14, 0xc5, 0xe5, 0xa4, 0xfd, 0xd4, 0xde, 0x8f, 0xfe, 0x73, 0x8b, 0x14, 0x95, 0x25, 0x74, 0xea,
	0x14, 0xab, 0x49, 0x11, 0x4c, 0x48, 0x48, 0x0c, 0x0c, 0xb0, 0xb4, 0xbc, 0x40, 0x12, 0x5d, 0xb5,
	0x95, 0x5c, 0x6c, 0x6c, 0x07, 0x91, 0x67, 0xe2, 0x25, 0x91, 0x13, 0x4c, 0x4b, 0x60, 0xe8, 0x94,
	0xe4, 0xa7, 0x7b, 0xcf, 0x39, 0x3e, 0x31, 0xdc, 0x6e, 0x76, 0x66, 0x5b, 0x64, 0x51, 0x2e, 0xf6,
	0xec, 0x51, 0xbc, 0x6c, 0x9e, 0x52, 0x95, 0x6f, 0xaf, 0xd9, 0x76, 0xb7, 0x11, 0x4c, 0xa3, 0x7a,
	0xdb, 0xe5, 0xc8, 0xf0, 0x3d, 0xdd, 0x4b, 0x8e, 0x9a, 0x19, 0xd4, 0x86, 0xc9, 0xac, 0x7a, 0x46,
	0x52, 0x09, 0x23, 0xa8, 0x27, 0xb3, 0x59, 0x04, 0x83, 0x75, 0x5a, 0x3e, 0x20, 0xe7, 0x62, 0x85,
	0xaf, 0x05, 0x6a, 0x43, 0x2f, 0x80, 0xe8, 0x80, 0x84, 0x64, 0xfe, 0x3f, 0xee, 0x45, 0x32, 0x8b,
	0x9e, 0x51, 0x9b, 0xb5, 0x51, 0x45, 0xbe, 0x22, 0x7a, 0xb6, 0x80, 0xde, 0x61, 0x5e, 0xf2, 0x92,
	0xf6, 0xc1, 0x53, 0xf5, 0x78, 0x77, 0xe5, 0x29, 0x4d, 0x87, 0xe0, 0xa3, 0x52, 0x81, 0x57, 0x01,
	0xfb, 0x3a, 0xbb, 0x84, 0xd1, 0x3d, 0x72, 0x34, 0x58, 0x68, 0x54, 0xce, 0xe4, 0xcc, 0x99, 0x74,
	0xad, 0x6a, 0x02, 0x83, 0xe3, 0x91, 0xd3, 0x74, 0x19, 0x0c, 0x6d, 0xb4, 0x3b, 0xa5, 0xd2, 0xb2,
	0x91, 0xdd, 0xff, 0x33, 0x7b, 0x0c, 0xfd, 0xa3, 0x85, 0xd3, 0x4c, 0x72, 0xe8, 0x7e, 0x6b, 0xd0,
	0x09, 0xb4, 0x6d, 0x7d, 0x8b, 0xaf, 0x8d, 0xfa, 0xc3, 0xd1, 0x38, 0xf0, 0x43, 0x32, 0x6f, 0xd7,
	0x34, 0x76, 0x34, 0x09, 0x5a, 0x21, 0x99, 0x77, 0x6a, 0x9a, 0x38, 0xba, 0x0c, 0xda, 0xa1, 0xef,
	0x14, 0x96, 0xf1, 0x07, 0x81, 0x96, 0x75, 0xa1, 0x31, 0x74, 0x5c, 0xbb, 0x74, 0x6c, 0xf3, 0x37,
	0xfe, 0xcd, 0x74, 0xf4, 0x13, 0xda, 0x33, 0xdc, 0x00, 0x1c, 0xba, 0xa3, 0xe7, 0x76, 0xe0, 0x57,
	0xdd, 0xd3, 0x71, 0x13, 0xdb, 0xcd, 0xab, 0xfa, 0x6c, 0x55, 0x1f, 0x74, 0xe2, 0xea, 0x3a, 0xee,
	0x73, 0x4a, 0x1b, 0x54, 0xf2, 0x32, 0xfb, 0x57, 0xdd, 0x9e, 0xe4, 0x33, 0x00, 0x00, 0xff, 0xff,
	0x9b, 0x83, 0x34, 0xed, 0x7f, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TestClient is the client API for Test service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TestClient interface {
	SayHello(ctx context.Context, in *SayHelloRequest, opts ...grpc.CallOption) (*SayHelloReply, error)
	Deleteuser(ctx context.Context, in *DeleteuserRequest, opts ...grpc.CallOption) (*DeleteuserReply, error)
	TestArray(ctx context.Context, in *TestArrayRequest, opts ...grpc.CallOption) (*TestArrayReply, error)
}

type testClient struct {
	cc *grpc.ClientConn
}

func NewTestClient(cc *grpc.ClientConn) TestClient {
	return &testClient{cc}
}

func (c *testClient) SayHello(ctx context.Context, in *SayHelloRequest, opts ...grpc.CallOption) (*SayHelloReply, error) {
	out := new(SayHelloReply)
	err := c.cc.Invoke(ctx, "/pb.Test/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *testClient) Deleteuser(ctx context.Context, in *DeleteuserRequest, opts ...grpc.CallOption) (*DeleteuserReply, error) {
	out := new(DeleteuserReply)
	err := c.cc.Invoke(ctx, "/pb.Test/Deleteuser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *testClient) TestArray(ctx context.Context, in *TestArrayRequest, opts ...grpc.CallOption) (*TestArrayReply, error) {
	out := new(TestArrayReply)
	err := c.cc.Invoke(ctx, "/pb.Test/TestArray", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TestServer is the server API for Test service.
type TestServer interface {
	SayHello(context.Context, *SayHelloRequest) (*SayHelloReply, error)
	Deleteuser(context.Context, *DeleteuserRequest) (*DeleteuserReply, error)
	TestArray(context.Context, *TestArrayRequest) (*TestArrayReply, error)
}

// UnimplementedTestServer can be embedded to have forward compatible implementations.
type UnimplementedTestServer struct {
}

func (*UnimplementedTestServer) SayHello(ctx context.Context, req *SayHelloRequest) (*SayHelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (*UnimplementedTestServer) Deleteuser(ctx context.Context, req *DeleteuserRequest) (*DeleteuserReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Deleteuser not implemented")
}
func (*UnimplementedTestServer) TestArray(ctx context.Context, req *TestArrayRequest) (*TestArrayReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TestArray not implemented")
}

func RegisterTestServer(s *grpc.Server, srv TestServer) {
	s.RegisterService(&_Test_serviceDesc, srv)
}

func _Test_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SayHelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Test/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestServer).SayHello(ctx, req.(*SayHelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Test_Deleteuser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteuserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestServer).Deleteuser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Test/Deleteuser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestServer).Deleteuser(ctx, req.(*DeleteuserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Test_TestArray_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestArrayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestServer).TestArray(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Test/TestArray",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestServer).TestArray(ctx, req.(*TestArrayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Test_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Test",
	HandlerType: (*TestServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Test_SayHello_Handler,
		},
		{
			MethodName: "Deleteuser",
			Handler:    _Test_Deleteuser_Handler,
		},
		{
			MethodName: "TestArray",
			Handler:    _Test_TestArray_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/LongMarch7/higo/service/examples/test/pb/test.proto",
}
